version: '3.8'

services:
  redis:
    image: redis
    environment: { TERM: xterm }
    ports: ["6379:6379"]
    restart: unless-stopped
    networks:
      - ${PROJECT_NAME}
  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - ${PROJECT_NAME}
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - ${PROJECT_NAME}
    restart: unless-stopped
  app:
    image: 'magento'
    build:
      dockerfile: ./docker/apache/Dockerfile
      args:
        SERVER_NAME: ${SERVER_NAME}
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./magento/:/var/www/html:rw,cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/000-custom.ini
    networks:
      - ${PROJECT_NAME}
    ports:
      - 443:443
      - 80:80
      - 8080:80
    depends_on:
      - redis
      - mysql
      - elasticsearch
    env_file:
      - ./.env
  mailhog:
    image: mailhog/mailhog
    ports:
        - 1025:1025 
        - 8025:8025 
    networks:
      - ${PROJECT_NAME}


networks:
  magento-project:
    name: NETWORK_NAME